development:
  adapter: postgresql
  encoding: unicode
  database: resume_development
  pool: 5
  username: resume
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: resume_test
  pool: 5
  username: resume
  password: password1